### ISSUE TITLE
explicit-function-return-type options

### ISSUE THREAD

**Issue by 43081j** [nzakas/eslint-plugin-typescript#123]
I like the idea of requiring explicit return types for methods and functions, as it makes the source very clear. However, requiring it on arrow functions seems OTT.

Could we possibly add a parameter to this or an options object to turn it off for arrow functions?

Happy to try a PR if nobody else is up for it...

**Comment by mightyiam** [comment]
I am not helped by #125, because my style is to use arrow functions wherever it is possible (where it is okay to have `this` bound). Which is most cases.

So, I ask myself, what is the common case, where a function would be exempt from this rule.

How about when:
1. it is a function or arrow function expression AND
2. it is not saved into a variable (right side of an assignment expression)

This way:
```ts
function functionDeclaration (): Must {}
const functionExpression = function (): Must {}
const arrowFunctionExpression = (): Must => {}
(function () {})() // exempt
setTimeout(function namedFunctionExpression () {}, 1000) // exempt
document.body.addEventListener('mousemove', () => {}) // exempt
const a = [1, 2, 3].map(n => n * 2) //exempt
```
